### ISSUE TITLE
 Is this document not finished yet

### ISSUE THREAD

**Issue by Universe-Yoyo** [jakdot/pyactr#1]
@jakdot Is this document not finished yet？——“Computing dynamic meanings:Building integrated competence-performance theories for formal semantics”

**Comment by BenDerPan** [comment]
@Universe-Yoyo I am looking for the full one, too. @jakdot The book_manual.pdf is not a full version, Is it still in writing? I am new to act-r theory, and I use python. The lisp version is not easy to understand for me.

**Comment by abrsvn** [comment]
We're still in the process of writing it. It'll come out as a book once we're done with it.

**Comment by jakdot** [comment]
Hi, as abrsvn said, we are in the process of writing the document/book. What's currently available should give you a good idea of how the symbolic system of ACT-R is done in pyactr.

Additionally, to learn more about ACT-R and pyactr I would recommend to explore tutorials.
You can find the full description of ACT-R tutorials here, under the heading Tutorial Units:
http://act-r.psy.cmu.edu/software/
These are official *Lisp ACT-R* tutorials, but I reimplemented quite a few tutorial models in pyactr, check the folder tutorials.
Probably, the best way to proceed is to study each tutorial unit, read pdf files and compare the Lisp code and the pyactr code.

Btw, if anyone wants to practice pyactr by coding missing Lisp ACT-R tutorial models, let me know, I'd be happy to consult this with you and add new models into future versions of pyactr.

**Comment by BenDerPan** [comment]
I tried [jact-r](http://cog.cs.drexel.edu/act-r/), too. The driving model looks good, it can automatic driving a car. But I am not familiar to java, and I wonder if pyactr supports think-decision-action like that, is there any APIs available to do that?

**Comment by jakdot** [comment]
@BenDerPan When you talk about jact-r, you probably mean Java ACT-R, right? That's the package that you link. jACT-R is a different java implementation.
You would have to be a bit more specific about the API you have in mind here, I am not sure I understand this. Also, please, it's better if you start it as a different issue, unless it's related to documentation and book_manual.pdf.

**Comment by jakdot** [comment]
Hi, for anyone interested, I have now added a short intro into pyactr (and ACT-R) on the wiki page of pyactr:
https://github.com/jakdot/pyactr/wiki

**Comment by soojijp** [comment]
thank you for your great work!
I am wondering if you are also implementing some ACT-R/pm extension features(such as peck, peck-recoil, ply) to this python version as well.

Thanks :)

**Comment by godnnness** [comment]
hi, when I  see the Tutorial,I found that there is missing "-" the negative test modifier in the LHS
![image](https://user-images.githubusercontent.com/50583143/64579976-4e70c500-d3b7-11e9-91ca-cdf0607ba5c8.png)

**Comment by godnnness** [comment]
which  is in ACT-R Tutorial Unit one - P18 ,but I don't know there is maybe some other ways to implementation

**Comment by jakdot** [comment]
> hi, when I see the Tutorial,I found that there is missing "-" the negative test modifier in the LHS
> ![image](https://user-images.githubusercontent.com/50583143/64579976-4e70c500-d3b7-11e9-91ca-cdf0607ba5c8.png)

Hi, the negative test modifier is done by using "~". You just put "~" in front of the *value* in the LHS and leave no space between "~" and the actual negated value (note that in Lisp ACT-R, "-" is normally put in front of the name of the slot, not the value).

**Comment by godnnness** [comment]
Thank you very much for your reply. I have been researching pyactr recently and I am looking forward to your book publishing. My job is to use ACT-R to control the speed-distance curve tracking of high-speed trains, which requires real-time, accuracy, and nonlinearity. I don't know if this works, so I try to use pyactr instead of lisp. It can be combined with some libraries in python, maybe it will help me. I will be grateful if I can get your help/suggestions!
![image](https://user-images.githubusercontent.com/50583143/64677969-2febf600-d4ab-11e9-9cf6-726ace9a5d96.png)

**Comment by godnnness** [comment]
I found that your program uses pyactr in combination with pymc3, pandas, etc., so whether you can use machine learning and other methods to build a speed-distance curve tracking algorithm in conjunction with pyact-r.

**Comment by jakdot** [comment]
The book on pyactr has recently been published by Springer. The book is open access and freely available here:

www.doi.org/10.1007/978-3-030-31846-8

The book goes step by step through explaining how pyactr can be used to build ACT-R models and has many many examples of cognitive models. It also shows how pyactr can be combined with probabilistic programming (pymc3) to develop Bayesian ACT-R models.
