### ISSUE TITLE
Comment error in "makechunk"?

### ISSUE THREAD

**Issue by asmaloney** [jakdot/pyactr#17]
In `makechunk` the comment says:

> For example:
    >>> makechunk(nameofchunk='example0', typename='chunktype_example0', value='one')
    chunktype_example0(value= one)
    This creates a chunk of type chunk1, which has one slot (value) and the value of that slot is one.

I think it should read:

> For example:
    >>> makechunk(nameofchunk='example0', typename='**chunk1**', value='one')
    **chunk1**(value= one)
    This creates a chunk of type chunk1, which has one slot (value) and the value of that slot is one.

**Comment by jakdot** [comment]
fixed
