### ISSUE TITLE
u5_fan tutorial: nonempty?

### ISSUE THREAD

**Issue by asmaloney** [jakdot/pyactr#27]
The u5_fan tutorial has the following:

```python

        self.model.productionstring(name="harvesting_person", string="""
        =g>
        isa     sentence_goal
        arg2    =location
        state   harvest_person
        =retrieval>
        isa     nonempty
        ==>
        =g>
        isa     sentence_goal
        state   harvest_location
        arg1    =retrieval
        +retrieval>
        isa     meaning
        word    =location""")

        self.model.productionstring(name="harvesting_location", string="""
        =g>
        isa     sentence_goal
        state   harvest_location
        =retrieval>
        isa     nonempty
        ?retrieval>
        state   free
        ==>
        =g>
        isa     sentence_goal
        state   get_retrieval
        arg2    =retrieval""")
```

Where is `nonempty` defined? It's not a keyword in the system (and no mention of it in the book), so it doesn't seem to be treated specially, and it's not defined elsewhere in the file. How is it matching? Is the chunk type ignored for matches?

**Comment by jakdot** [comment]
nonempty did not do anything since isa chunk is not matching. I think I had it there either because of some older properties of chunkstring, which required specifying at least one slot-value pair, or because of some match with Lisp ACT-R tutorials. I removed it now.
