### ISSUE TITLE
{suggestion} Tag releases

### ISSUE THREAD

**Issue by asmaloney** [jakdot/pyactr#39]
I was trying to find which commit corresponds to the currently released 0.3.1, but there are no tags in the repo.

I would suggest tagging each release (and creating a release on GitHub for it) so it's easy to find.

I _think_ 0.3.1 corresponds to 6ba34b79817c93f4211998f379b381205dbfce56.

**Comment by jakdot** [comment]
Thanks for the tip, my github skills are quite limited... definitely good to tag releases, I will try to keep that in mind from now on.

**Comment by jakdot** [comment]
Thanks for clearing this up and sending the links, that's useful. If I have more questions about tagging and releasing, I'll let you know (I hope that's ok).

**Comment by asmaloney** [comment]
> I hope that's ok

Absolutely!  I'm happy to help.
