### ISSUE TITLE
Error when following "Getting Started II"

### ISSUE THREAD

**Issue by sunox1** [jakdot/pyactr#4]
Hello.

I have been following along the "Getting Started" tutorials to get a feel for ACT-R. However, when running the simulation at the end of "Model 4" I get an error: `raise KeyError from None`, because we try to pop `playing_memory.retrieval` which appears to be empty. It appears that there may be something wrong with the code that generates 9 `recallfailed` productions, as `playing_memory.retrieval` is not empty before we replace the single `recallfailed` production with the loop that creates the 9.

If I remove `playing_memory.retrieval.pop()` the simulation runs until key press #8 when it runs out of productions, and after a few seconds of `AUTOMATIC BUFFERING` of the visual module Python crashes with exit code 1.

I should perhaps add that I am using Python 3.7.3.

I am new to ACT-R, and for that matter to Python as well, so apologies if this is due to some mistake I've made. Thank you for making pyactr--it looks easier to pick up than vanilla ACT-R, and I'm hoping to be able to use it in an upcoming project.

Cheers.

**Comment by jakdot** [comment]
Thanks a lot for your interests in the package.

How did you run the code? If you want to test it on your own computer, I would recommend that you install jupyter notebook (see [https://jupyter.org/](url)). After that, go to the folder docs, start jupyter and run the code Getting started II.ipynb. It should work fine (I just tested it with python3.7, it works; for details on jupyter, see the website).

Alternatively, you can copy and run the following code (this is just the whole Getting started II site but the text is left out). It should work and not throw any errors.

`
import pyactr as actr
environment = actr.Environment()
playing_memory = actr.ACTRModel(environment=environment)

memory = [{}, {"A": {'text': 'A', 'position': (100, 100)}}]

goal = playing_memory.set_goal("goal")
actr.chunktype("playgame", "game, activity, key, object")
initial_chunk = actr.makechunk(typename="playgame", game="memory", key="1")
goal.add(initial_chunk)


playing_memory.productionstring(name="startplaying", string="""
=goal>
isa  playgame
game memory
activity None
==>
=goal>
isa playgame
activity presskey""") #to be modified later

playing_memory.productionstring(name="presskey", string="""
=goal>
isa  playgame
game memory
activity presskey
key =k
==>
+manual>
isa _manual
cmd press_key
key =k
=goal>
isa playgame
activity attend""")

playing_memory.productionstring(name="attendobject", string="""
=goal>
isa  playgame
game memory
activity attend
=visual_location>
isa _visuallocation
?manual>
state free
==>
=goal>
isa playgame
activity storeobject
+visual>
isa _visual
cmd     move_attention
screen_pos =visual_location""")

playing_memory.productionstring(name="storeobject", string="""
=goal>
isa  playgame
game memory
activity storeobject
=visual>
isa _visual
value =v
==>
=goal>
isa playgame
activity None
object =v""")


simulation = playing_memory.simulation(gui=False, environment_process=environment.environment_process, stimuli=memory, triggers='1')
simulation.run()


print(goal)


playing_memory.productionstring(name="startplaying", string="""
=goal>
isa  playgame
game memory
activity None
object None
==>
=goal>
isa playgame
activity presskey""")


playing_memory.productionstring(name="continueplaying", string="""
=goal>
isa  playgame
game memory
activity None
object ~None
==>
=goal>
isa playgame
game memory
activity recall""")


playing_memory.productionstring(name="recallvalue", string="""
=goal>
isa  playgame
game memory
activity recall
object =val
==>
=goal>
isa  playgame
game memory
activity checkrecalled
+retrieval>
isa playgame
object =val""")

playing_memory.productionstring(name="recallsuccessful", string="""
=goal>
isa  playgame
game memory
activity checkrecalled
object =val
?retrieval>
buffer full
=retrieval>
isa playgame
key =k
==>
=goal>
isa playgame
key =k
activity done""")


playing_memory.productionstring(name="recallfailed", string="""
=goal>
isa  playgame
game memory
activity checkrecalled
key 1
object =val
?retrieval>
state error
==>
~goal>
+goal>
isa playgame
game memory
activity presskey
key 2""")

memory = [{}, {"A": {'text': 'A', 'position': (100, 100)}}, {"A": {'text': 'A', 'position': (100, 100)}}]


goal.add(initial_chunk)
simulation = playing_memory.simulation(gui=False, environment_process=environment.environment_process, stimuli=memory, triggers=['1', '2', '3'])
simulation.run(max_time=2)

print(goal)


print(playing_memory.decmem)


for i in range(1, 9):
    playing_memory.productionstring(name="recallfailed" + str(i), string="""
    =goal>
    isa  playgame
    game memory
    activity checkrecalled
    key """+ str(i) +"""
    object =val
    ?retrieval>
    state error
    ==>
    ~goal>
    +goal>
    isa playgame
    game memory
    activity presskey
    key """ + str((i+1)%10))
    
playing_memory.productionstring(name="recallfailed9", string="""
=goal>
isa  playgame
game memory
activity checkrecalled
key 0
object =val
?retrieval>
state error
==>
~goal>""")


memory = [{}] + [{i: {'text': i, 'position': (100, 100)}} for i in "BCDEFGHDIJ"]
goal.add(initial_chunk)
playing_memory.retrieval.pop()
simulation = playing_memory.simulation(environment_process=environment.environment_process, stimuli=memory, triggers=[str(i%10) for i in range(1,11)] + ['0'])


while True:
    simulation.step()
    if simulation.current_event.action == "RULE FIRED: recallsuccessful":
        break


print(goal)

print(simulation.show_time())


playing_memory.model_parameters["subsymbolic"] = True

goal.add(initial_chunk)
playing_memory.retrieval.pop()
for i in playing_memory.decmem.copy():
    playing_memory.decmem.pop(i)
simulation = playing_memory.simulation(environment_process=environment.environment_process, stimuli=memory, triggers=[str(i%10) for i in range(1,11)] + ['0'])


while True:
    simulation.step()
    if simulation.current_event.action == "RULE FIRED: recallsuccessful":
        break
    if simulation.show_time() > 10: #10 seconds is enough time to go through the cards
        print("Nothing found, breaking")
        break
`

**Comment by sunox1** [comment]
Thank you for the response!

The code you posted works fine. I suppose I should have tried running the code without changes myself first. When I was following the example I was overwriting 'old' code whenever it seemed appropriate, and it looks like a missing `goal.add(initial_chunk)` was the cause.

Thanks again.

**Comment by jakdot** [comment]
Great to hear it works now.
