### ISSUE TITLE
Screen positions and visual_location

### ISSUE THREAD

**Issue by TjeerdFokkens** [jakdot/pyactr#6]
Thank you for your wonderful work in implementing ACT-R into Python!
I read your book and think that pyactr has a lot of potential.
In implementing my own model using pyactr, however, I encountered the following anomaly.

When starting from position (0,0):
`environment = actr.Environment(focus_position=(0,0))`
...and having three stimuli at positions (0,100), (100,100) and (50,50):
```
stim = {1: {'text': 'A', 'position': (0, 100)},
         2: {'text': "B", 'position': (100, 100)},
         3: {'text': 'C', 'position': (50, 50)}}
```
...the production rule:
```
...
+visual_location>
    isa   _visuallocation
    screen_x    closest
```
...selects the stimulus 'C' at position (50,50).

How is this possible?

One would think that 'A' at (0,100) should be selected, because its x-coordinate is closest to the starting position (it's indeed actually equal to it).

Am I missing something or is this a 'real' bug? I'm looking forward to some advice on this. Thanks in advance!

**Comment by jakdot** [comment]
Hi,

Thanks for your comments and interest in pyactr!

"closest" actually calculates what element is closest to the current focus and attends that object, irrespective of whether this is an x-coordinate or y-coordinate. Somewhat misleadingly, it happens to appear as the value of the slot screen_x but this is just a consequence of the fact that every value has to appear next to a slot. This particular keyword (closest) ignores what slot it was associated with (you could just as well write "screen_y closest" and the result should be the same). 

There is another special keyword, onewayclosest, which does what you expected closest to do, namely, it only measures the distance to an object on one of the axes. I am aware that this is suboptimal and somewhat confusing. It might be cleared up in future versions of pyactr but I need to first decide how to syntactically treat values that are more general than any of the slots.

Hope this helps!

**Comment by TjeerdFokkens** [comment]
Perfect! Yes, that greatly helps. onewayclosest does the job. Thank you very much and the best of luck in making future versions!
